#!/bin/bash

### ABOUT
# fgdata_downloader
# This script will download FlightGear data.
# These are files and folders that contains 3D models, textures and
# other files required to run FlightGear. It will take a couple of GBs.

### AUTHOR
# This software was created by Megaf - https://github.com/Megaf
# On the 20/10/2020

### LICENSE
########################################################################
#                                                                      #
#                       FREE AS IN FREEDOM LICENSE                     #
#                           FAIFL Version 0.2                          #
#                             October 2020                             #
#                                                                      #
#           Copyright (C) 2020 Megaf (https://github.com/Megaf/)       #
#                     <mmegaf [at] gmail [dot] com>                    #
#                                                                      #
# Everyone, anyone, anything or any company or organization, human,    #
# plant, apache helicopter, alive or not, form of life or not, is/are  #
# allowed to copy, modify, distribute, change, charge or do anything   #
# they/ones want with anything or whatever this license is, attached   #
# to or licensing.                                                     #
#                                                                      #
# This thing, software, hardware, piece, object, art, or whatever that #
# is been licensed under FAIFL (Free As In Freedom License) can be     #
# used, shared, copied, sold, modified, changed, adapted, or whatever  #
# you want to do as long as the following terms are understood and met.#
#                                                                      #
# (1) This that is licensed under FAIFL comes as it is.                #
# (2) This that is licensed under FAIFL it is not covered under any    #
# warranty.                                                            #
# (3) There is no warranty or guarantee that this that is licensed     #
# under FAIFL works at all.                                            #
# (4) This that is licensed under FAIFL may be dangerous and cause     #
# harm and loss of property.                                           #
# (5) Changing this license is not allowed.                            #
# (6) The creator, owner, author of this that is licensed under FAIFL  #
# shall not be liable,responsible or accused in any way for anything   #
# at all.                                                              #
#                                                                      #
########################################################################

installdir="$(envsubst < INSTALL_LOCATION)" # Directory where FlightGear data will be downloaded to.
read -r version < VERSION # Using read command to get version information from the file VERSION.

major_stable_version="2020.3"
minor_stable_version=".4"
git_stable_version=release/"$major_stable_version"

major_testing_version="nightly"
minor_testing_version="latest"
git_testing_version="next"

### INTRODUCTION PART
clear
echo "#====== Welcome to FlightGearBuilder $version !"
echo "#====== This script will download FlightGear data files."
echo ""
echo "#====== You must use flags '--stable'/'--next' and '--git'/'--wget' to tell this script"
echo "#====== which version of FlightGear Data you want to donwload and if you want to use"
echo "#====== git or wget to download it."
echo ""

# Waits for the user to press a key to continue.
echo ""
echo "#====== Press any key to continue or Ctrl + C to cancel."
read -rsn1
clear

echo "#====== Deleting old data files."
rm -rf -- "${installdir:?}"/data
mkdir -p "${installdir:?}" || exit
cd "$installdir" || exit

download_fgdata_stable_git(){
    git clone -b "$git_stable_version" --depth=1 git://git.code.sf.net/p/flightgear/fgdata data
}

download_fgdata_stable_wget(){
    wget -c http://download.flightgear.org/builds/"$major_stable_version"/FlightGear-"$major_stable_version""$minor_stable_version"-data.tar.bz2 -O fgdata.tar.bz2
    tar jxfv fgdata.tar.bz2 && rm -f -- ./fgdata.tar.bz2 && mv fgdata data
}

download_fgdata_next_git(){
    git clone -b "$git_testing_version" --depth=1 git://git.code.sf.net/p/flightgear/fgdata data
}

download_fgdata_next_wget(){
    wget -c http://download.flightgear.org/builds/"$major_testing_version"/FlightGear-"$minor_testing_version"-data.tar.bz2 -O fgdata.tar.bz2
    tar jxfv fgdata.tar.bz2 && rm -f -- ./fgdata.tar.bz2 && mv fgdata data
}

if [[ "$*" = *"--stable"* ]] && [[ "$*" = *"--wget"* ]]; then
    echo "selected $*" && download_fgdata_stable_wget
fi

if [[ "$*" = *"--stable"* ]] && [[ "$*" = *"--git"* ]]; then
    echo "selected $*" && download_fgdata_stable_git
fi

if [[ "$*" = *"--next"* ]] && [[ "$*" = *"--wget"* ]]; then
    echo "selected $*" && download_fgdata_next_wget
fi

if [[ "$*" = *"--next"* ]] && [[ "$*" = *"--git"* ]]; then
    echo "selected $*" && download_fgdata_next_git
fi
