#!/bin/bash

### ABOUT
# flightgear_uninstaller
# This script will remove all files created and downloaded by FlightGearBuilder.

### AUTHOR
# This software was created by Megaf - https://github.com/Megaf
# On the 20/10/2020

### LICENSE
########################################################################
#                                                                      #
#                       FREE AS IN FREEDOM LICENSE                     #
#                           FAIFL Version 0.2                          #
#                             October 2020                             #
#                                                                      #
#           Copyright (C) 2020 Megaf (https://github.com/Megaf/)       #
#                     <mmegaf [at] gmail [dot] com>                    #
#                                                                      #
# Everyone, anyone, anything or any company or organization, human,    #
# plant, apache helicopter, alive or not, form of life or not, is/are  #
# allowed to copy, modify, distribute, change, charge or do anything   #
# they/ones want with anything or whatever this license is, attached   #
# to or licensing.                                                     #
#                                                                      #
# This thing, software, hardware, piece, object, art, or whatever that #
# is been licensed under FAIFL (Free As In Freedom License) can be     #
# used, shared, copied, sold, modified, changed, adapted, or whatever  #
# you want to do as long as the following terms are understood and met.#
#                                                                      #
# (1) This that is licensed under FAIFL comes as it is.                #
# (2) This that is licensed under FAIFL it is not covered under any    #
# warranty.                                                            #
# (3) There is no warranty or guarantee that this that is licensed     #
# under FAIFL works at all.                                            #
# (4) This that is licensed under FAIFL may be dangerous and cause     #
# harm and loss of property.                                           #
# (5) Changing this license is not allowed.                            #
# (6) The creator, owner, author of this that is licensed under FAIFL  #
# shall not be liable,responsible or accused in any way for anything   #
# at all.                                                              #
#                                                                      #
########################################################################

# Directory where everything will be installed at.
installdir="$HOME/FlightGear"
# Directory where the source codes will be downloaded to.
download_dir="/tmp/FlightGear_Sources"
# Temporary directory where cmake will run from.
buildir="/dev/shm/FlightGear_Compiler_Output"
version="$(cat VERSION)"

### INTRODUCTION PART
clear
echo ""
echo "#====== Welcome to FlightGearBuilder $version !"
echo "#====== This script will remove all downloaded files, compiler left overs and"
echo "#====== uninstall FlightGear that was previously installed using FlightGearBuilder"

# Waits for the user to press a key to continue.
echo ""
echo "#====== Press any key to continue or Ctrl + C to cancel."
read -rsn1
clear

# Removing files.
echo "#====== Removing previously downloaded files."
rm -r $download_dir
echo "#====== Removing Compiling left overs."
rm -r $buildir
echo "#====== Uninstalling FlightGear."
rm -r $installdir
