#!/bin/bash

# FlightGearBuilder.sh

### AUTHOR
# This software was created by Megaf - https://github.com/Megaf
# On the 20/10/2020

### LICENSE
########################################################################
#                                                                      #
#                       FREE AS IN FREEDOM LICENSE                     #
#                           FAIFL Version 0.2                          #
#                             October 2020                             #
#                                                                      #
#           Copyright (C) 2020 Megaf (https://github.com/Megaf/)       #
#                     <mmegaf [at] gmail [dot] com>                    #
#                                                                      #
# Everyone, anyone, anything or any company or organization, human,    #
# plant, apache helicopter, alive or not, form of life or not, is/are  #
# allowed to copy, modify, distribute, change, charge or do anything   #
# they/ones want with anything or whatever this license is, attached   #
# to or licensing.                                                     #
#                                                                      #
# This thing, software, hardware, piece, object, art, or whatever that #
# is been licensed under FAIFL (Free As In Freedom License) can be     #
# used, shared, copied, sold, modified, changed, adapted, or whatever  #
# you want to do as long as the following terms are understood and met.#
#                                                                      #
# (1) This that is licensed under FAIFL comes as it is.                #
# (2) This that is licensed under FAIFL it is not covered under any    #
# warranty.                                                            #
# (3) There is no warranty or guarantee that this that is licensed     #
# under FAIFL works at all.                                            #
# (4) This that is licensed under FAIFL may be dangerous and cause     #
# harm and loss of property.                                           #
# (5) Changing this license is not allowed.                            #
# (6) The creator, owner, author of this that is licensed under FAIFL  #
# shall not be liable,responsible or accused in any way for anything   #
# at all.                                                              #
#                                                                      #
########################################################################

### ABOUT THIS SOFTWARE
# This script will compile from the source code OpenSceneGraph, PLIB, SimGear libraries and FlightGear Flight Simulator.
# Using the flags and variables set bellow.

# Uses ccache (https://ccache.dev/) if it's available, to speed rebuilds
export PATH="/usr/lib/ccache:${PATH}"

# Directory where everything will be installed at.
installdir="$HOME/FlightGear"
# Directory where the source codes will be downloaded to.
download_dir="/tmp/FlightGear_Sources"
# Temporary directory where cmake will run from.
buildir="/dev/shm/FlightGear_Compiler_Output"
version="$(cat VERSION)"

# Compiler flags
cflags="-march=native -mtune=native -O3 -pipe -mfpmath=both"
buildtype="Release" # Build type, Release for better performance. All flags in this script are for Release type.

rm -rf $buildir # Deleting old build files, for a clean build.
rm -rf $installdir/bin $installdir/lib $installdir/include # Delete old installed binaries and libs.
# Creating directories where cmake will run from.
mkdir -p $buildir/OSG $buildir/PLIB $buildir/SimGear $buildir/FlightGear

# Variables defining which branches will be used for each repository.
ncores="$(nproc)" # Sets the number of compiler tasks according to number of logical cpus in your system

### INTRODUCTION PART
clear
echo ""
echo "#====== Welcome to FlightGearBuilder $version !"
echo "#====== This script will compile OpenSceneGraph, PLIB, SimGear and FlightGear."

# Waits for the user to press a key to continue.
echo ""
echo ""
echo "#====== Press any key to continue."
read -rsn1
clear

# TODO
# Add checks to see if everything is downloaded/present.

# Now the script will run cmake and make and make install for each component.
echo ""
echo "#====== Compiling OpenSceneGraph."
cd $buildir/OSG && cmake $download_dir/OSG -DCMAKE_BUILD_TYPE="$buildtype" -DOpenGL_GL_PREFERENCE=LEGACY -DCMAKE_CXX_FLAGS_RELEASE="$cflags" -DCMAKE_C_FLAGS_RELEASE="$cflags" -DCMAKE_INSTALL_PREFIX=$installdir
make -j $ncores && echo "#====== Installing OpenSceneGraph." && make install && rm -rf $buildir/OSG

echo ""
echo "#====== If something went wrong when compiling OpenSceneGraph then make sure"
echo "#====== you have all dependencies required."

echo ""
echo "#====== Compiling PLIB."
cd $buildir/PLIB && cmake $download_dir/PLIB -DCMAKE_BUILD_TYPE="$buildtype" -DOpenGL_GL_PREFERENCE=LEGACY -DCMAKE_CXX_FLAGS_RELEASE="$cflags" -DCMAKE_C_FLAGS_RELEASE="$cflags" -DCMAKE_INSTALL_PREFIX=$installdir
make -j $ncores && echo "#====== Installing PLIB." && make install&& rm -rf $buildir/PLIB

echo ""
echo "#====== If something went wrong when compiling PLIB then make sure"
echo "#====== you have all dependencies required."

echo ""
echo "#====== Compiling SimGear."
cd $buildir/SimGear && cmake $download_dir/SimGear -DCMAKE_BUILD_TYPE="$buildtype"  -DBUILD_TESTING=OFF -DENABLE_TESTS=OFF -DENABLE_SIMD_CODE=ON -DENABLE_SIMD=ON -DCMAKE_CXX_FLAGS_RELEASE="$cflags" -DCMAKE_C_FLAGS_RELEASE="$cflags" -DCMAKE_INSTALL_PREFIX=$installdir
make -j $ncores && echo "#====== Installing SimGear." && make install&& rm -rf $buildir/SimGear
echo "#====== If something went wrong when compiling SimGear then make sure"
echo "#====== you have all dependencies required."

echo ""
echo "#====== Compiling FlightGear."
cd $buildir/FlightGear && cmake $download_dir/FlightGear -DCMAKE_BUILD_TYPE="$buildtype" -DSYSTEM_FLITE=OFF -DENABLE_AUTOTESTING=OFF -DENABLE_SIMD=ON -DCMAKE_CXX_FLAGS_RELEASE="$cflags" -DCMAKE_C_FLAGS_RELEASE="$cflags" -DCMAKE_INSTALL_PREFIX=$installdir
make -j $ncores && echo "#====== Installing FlightGear." && make install && rm -rf $buildir/FlightGear

echo ""
echo "#====== If something went wrong when compiling FlightGear then make sure"
echo "#====== you have all dependencies required."

echo ""
echo "#====== Creating fgfs runner script."

# Creates $installdir/flightgear
# To learn more about fg home and root read http://wiki.flightgear.org/$FG_HOME and http://wiki.flightgear.org/$FG_ROOT
 
# Creates $installdir/flightgear
cat << EOF > $installdir/flightgear
#!/bin/bash
export LD_LIBRARY_PATH=$installdir/lib
export FG_HOME=$installdir/FG_HOME
export FG_ROOT=$installdir/data
$installdir/bin/fgfs \$*
EOF

chmod +x $installdir/flightgear # Sets it as executable

# Checking if the file was created.
if [ -e $installdir/flightgear ]; then

echo ""
echo "#====== fgfs runner created."
else
echo ""
echo "#====== Something went wrong when creating fgfs runner."
fi

echo ""
echo "#====== Done. Enter $installdir and run $installdir/flightgear to start the sim."
echo "#====== The command flightgear will take the same arguments as fgfs, such as flightgear --launcher" 
echo ""
echo "#====== If everything went well then you can run FlightGear"
echo "#====== by running the command ./flightgear or ./flightgear --launcher."
echo ""
echo "#====== Feel free to ask for help and contribute to this script at"
echo "#====== https://github.com/Megaf/FlightGearBuilder "
echo ""
